In [3]:
import numpy as np
x=np.matrix([[1,2,3],[4,5,6],[9,3,4],[2,3,3]])

In [12]:
pseu=np.transpose(x)
np.dot(np.dot(np.linalg.inv(np.dot(pseu,x)),pseu),x)

matrix([[  1.00000000e+00,  -1.94289029e-15,  -2.10942375e-15],
        [ -1.33226763e-15,   1.00000000e+00,  -1.99840144e-14],
        [  5.32907052e-15,   2.04281037e-14,   1.00000000e+00]])

In [15]:
pseu=np.matrix([[0,1,0,0],[0,0,1,0],[1,0,0,0]])
np.dot(np.dot(np.linalg.inv(np.dot(pseu,x)),pseu),x)

matrix([[  1.00000000e+00,   2.22044605e-16,   2.22044605e-16],
        [  0.00000000e+00,   1.00000000e+00,  -2.22044605e-16],
        [ -4.44089210e-16,  -4.44089210e-16,   1.00000000e+00]])

In [16]:
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [9, 3, 4],
        [2, 3, 3]])

In [18]:
np.dot(np.linalg.inv(np.dot(pseu,x)),pseu)

matrix([[-0.0952381 , -0.04761905,  0.14285714,  0.        ],
        [-1.80952381,  1.0952381 , -0.28571429,  0.        ],
        [ 1.57142857, -0.71428571,  0.14285714,  0.        ]])